[package]
name = "rtoml"
version = "0.1.0"
authors = ["Samuel Colvin <s@muelcolvin.com>"]
edition = "2018"

[lib]
name = "rtoml"
crate-type = ["cdylib"]

[dependencies]
toml = "0.5.5"

[dependencies.pyo3]
version = "0.8.5"
features = ["extension-module"]
